// Generated by CoffeeScript 1.10.0
var Utils;

module.exports = Utils = (function() {
  function Utils() {}

  Utils.prototype.getActiveShadowRoot = function() {
    console.log('Utils.getActiveShadowRoot: atom=' + atom);
    console.log('Utils.getActiveShadowRoot: atom.workspace.getActiveTextEditor()=', +atom.workspace);
    return atom.workspace.getActiveTextEditor().getElement().shadowRoot;
  };

  Utils.prototype.doIt = function() {
    return 7;
  };

  return Utils;

})();

//# sourceMappingURL=utils.js.map
