// Generated by CoffeeScript 1.10.0
var Utils;

module.exports = Utils = (function() {
  function Utils() {}

  Utils.prototype.getActiveShadowRoot = function() {};

  Utils.prototype.doIt = function() {
    return 7;
  };

  return Utils;

})();

//# sourceMappingURL=utils.js.map
