// Generated by CoffeeScript 1.10.0
var Utils;

Utils = require('../lib/utils');

fdescribe('Utils', function() {
  beforeEach(function() {
    return this.utils = new Utils();
  });
  return it('doIt works', function() {
    return expect(this.utils.doIt()).toEqual(7);
  });
});

//# sourceMappingURL=utils-spec.js.map
